org: techcatalog
app: catalog
service: catalog-backend

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-west-1
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: main.handler
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'
    enviroment:
      JWT_SECRET: ${param:JWT_SECRET}
      WEBHOOK_URL: ${param:WEBHOOK_URL}
      DETA_PROJECT_KEY: ${param:DETA_PROJECT_KEY}
      ADD_ITEM_PASSWORD: ${param:ADD_ITEM_PASSWORD}
